remote_theme: "mmistakes/so-simple-theme@3.2.0"

title: Octocat's homepage
description: Bookmark this to keep an eye on my project updates!
copyright: ""
footer_links: false
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

# Collections
collections: 
  projects:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # Projects defaults
  - scope:
      path: "_projects"
      type: projects
    values:
      layout: post
      comments: false
      share: false
